### ISSUE TITLE
Consumption Reporting - reportingInterval shall not be zero

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#120]
## Description
I am testing the v1.4.0-RC2. One finding regarding consumption reporting:
* If I update an existing `consumptionReportingConfiguration` using a `reportingInterval` value set to `0.1` I get a `204` response code so the configuration is updated. If I query the configuration afterwards `reportingInterval` is set to 0.
* 26.512 17.7.0 defines that `reportingInterval` shall be greater than zero: _The interval between two consecutive consumption reports. The value shall be greater than zero._
* Since the type of `reportingInterval` is  `DurationSec` and  shall be an Integer I assume this behavior is a minor bug and the AF is accepting Float values.

Please note that I am making direct REST calls to the AF and are not using the `m1-session-tool` in my tests.

**Comment by dsilhavy** [comment]
Confirmed, that the fix in #125 works

**Comment by davidjwbbc** [comment]
Closed by merge of #125
