### ISSUE TITLE
M1 | Metrics Provisioning Configuration OpenAPI models

### ISSUE THREAD

**Issue by stojkovicv** [5G-MAG/rt-5gms-application-function#134]
I am opening this thread to address potential bug mentioned in the comment of the [M1 Metrics Implementation discussion](https://github.com/5G-MAG/rt-5gms-application-function/issues/68).
The main issue here is the way on how to create Metrics Configuration ID. External OpenAPI function `msaf_api_metrics_reporting_configuration_create()` is declared in the way that it requires ID as an argument from the `Create` operation. On the other hand, there is an approved way to generate this ID within AF.

**Comment by rjb1000** [comment]
The fundamental problem is that _MetricsReportingConfiguration.metricsReportingConfigurationId_ is marked as `required` in the latest Rel-17 YAML, but isn't (yet) marked as `readOnly` to indicate that the value is assigned by the 5GMS AF.

As an interim measure, this can be taken care of by adding a suitable override file here:
- https://github.com/5G-MAG/rt-common-shared/tree/main/5gms/5G_APIs-overrides

**Comment by rjb1000** [comment]
The secondary problem is that the business logic in the 5GMS AF reference implementation appears to be accepting _MetricsReportingConfiguration.metricsReportingConfigurationId_ as an input value and storing it. This is incorrect. The code needs to ignore this value if provided as input.

**Comment by davidjwbbc** [comment]
Previously, to work around this issue, we wrote our own parser for the create and update operations which ignored the ID value. With the change to the openapi-generator templates and the introduction of `read-only` flags to some of the TS 26.512 OpenAPI YAML files, the generated object parser will ignore read-only fields on request parsing.

Adding the read-only flags to a version of the OpenAPI YAML file in the overrides is the best way to handle this now.

**Comment by rjb1000** [comment]
> Adding the read-only flags to a version of the OpenAPI YAML file in the overrides is the best way to handle this now.

OK. Great. So who is going to make this happen?

**Comment by dsilhavy** [comment]
@stojkovicv Please take care of this and create an override file here: https://github.com/5G-MAG/rt-common-shared/tree/main/5gms/5G_APIs-overrides. This change complements your implementation of M1 QoE Metrics Reporting.

**Comment by stojkovicv** [comment]
The TS 26.512 V17.6.0 M1 Metrics yaml configuration file seems to be partially correct, because for the `Create` operation, where ID is not needed - the `path` field was already specified to not require metrics ID. That seems correct.
However all 3 (or 4 with `patch`) other operations have different `path`, where ID is required indeed.

I've setted `readOnly` to true for `components` for metrics ID, with latest PR

**Comment by dsilhavy** [comment]
@stojkovicv @davidjwbbc Can we close this issue as https://github.com/5G-MAG/rt-common-shared/pull/30 has been merged?
