### ISSUE TITLE
Dynamic Policies Template retrieval missing fields

### ISSUE THREAD

**Issue by stojkovicv** [5G-MAG/rt-5gms-application-function#144]
## Description
`TS26512_CommonData.yaml#/components/schemas/M1QoSSpecification` defines `qoSSpecification` array of Dynamic Policies Template with `maxBtrUl` and `maxBtrDl` among others. 
Expected behaviour is to retrieve those values if they're previoulsy included in creation of Policy Template.

## How to reproduce
1. Start Application Function
2. Create a provisioning session
3. Create Policy Template for a provisioning session using following JSON data:

```
{
    "externalReference": "externalId",
    "state": "INVALID",

    "stateReason": {
        "type": "type"
    },

    "qoSSpecification": {
        "qosReference": "qosReference",
        "maxBtrUl": "560 Kbps", //value here
        "maxBtrDl": "500 Kbps", //value here
        "maxAuthBtrUl": "400 Kbps",
        "maxAuthBtrDl": "300 Kbps",
        "defPacketLossRateDl": 1,
        "defPacketLossRateUl": 1
    },
    
    "applicationSessionContext": {
        "sliceInfo": {
            "sst": 200,
            "sd": "000000"
        },
        "dnn": "test"
    },
    "chargingSpecification": {
        "sponId": "sponId",
        "sponStatus": "SPONSOR_ENABLED",
        "gpsi": [
            "msisdn-12345"
        ]    
    }
}
```
4. Using newly generated Policy Template UUID from `Location` header of the response, retrieve policy data. This is the output:

```
{
    "applicationSessionContext": {
        "dnn": "test",
        "sliceInfo": {
            "sd": "000000",
            "sst": 200
        }
    },
    "chargingSpecification": {
        "gpsi": [
            "msisdn-12345"
        ],
        "sponId": "sponId",
        "sponStatus": "SPONSOR_ENABLED"
    },
    "externalReference": "externalId",
    "policyTemplateId": "e5dc87f2-e2bd-41ee-9a07-5beb9bfff66e",
    "qoSSpecification": {
        "defPacketLossRateDl": 1,
        "defPacketLossRateUl": 1,
        "maxAuthBtrDl": "300 Kbps",
        "maxAuthBtrUl": "400 Kbps",
        "qosReference": "qosReference"
    },
    "state": "READY",
    "stateReason": {}
}
```

`maxBtrUl` and `maxBtrDl` are missing as part of `qoSSpecification` of the retrieved Policy Template.

**Comment by dsilhavy** [comment]
`maxBtrUl` and `maxBtrDl` are read-only fields and are ignored by the AF. If there are no values set for these two parameters internally by the AF, then they are also not included in the output (when calling M1 GET).

**Comment by dsilhavy** [comment]
@davidjwbbc Do you want to add anything here? Otherwise I suggest we close this issue.
