### ISSUE TITLE
QoE Metrics Reporting - M1 Provisioning - reportingInterval shall be greater than zero

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#145]
## Description
According to TS 26.512 Table 7.8.3-1 the `reportingInterval` shall be greater than zero:

> The time interval between successive metrics reports. **The value shall be greater than zero**.
If not specified, a single final report shall be sent after the media streaming session has ended.

The current implementation accepts values equal and below zero. Resulting output when reading the configuration afterwards

````json
{
    "reportingInterval": -1,
}
````

**Comment by rjb1000** [comment]
Looks like this will need to be validated manually (at least for the time being) since the underlying YAML data type for _DurationSec_ is a signed integer without a sensible minimum value of 0.

**Comment by rjb1000** [comment]
See also #146.

**Comment by dsilhavy** [comment]
Confirmed this is fixed with the latest changes
