### ISSUE TITLE
M1 - Consumption Reporting Provisioning API - Wrong response code for POST operation

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#156]
## Describe the bug

TS26512_M1_ConsumptionReportingProvisioning.yaml v 17.7.0 defines the response code for the path `/provisioning-sessions/{provisioningSessionId}/consumption-reporting-configuration` and the `post`operation. According to the YAML file the response code shall be `201`. 

Our implementation currently returns code `204`:

<img width="2107" alt="Bildschirmfoto 2024-04-26 um 09 41 28" src="https://github.com/5G-MAG/rt-5gms-application-function/assets/2427039/3db781c6-7538-464f-8989-d6b962dd9e65">

**Comment by rjb1000** [comment]
Agree with your analysis, @dsilhavy. The success response code for the _activateConsumptionReporting_ operation should be [_201 Created_ per the YAML](https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-17/TS26512_M1_ConsumptionReportingProvisioning.yaml#L30-48).

If @davidjwbbc can reproduce it, we should fix it.
