### ISSUE TITLE
M1 - Consumption Reporting Provisioning API - Missing Location Header

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#157]
## Describe the bug

TS26512_M1_ConsumptionReportingProvisioning.yaml v 17.7.0 defines the response headers for the path `/provisioning-sessions/{provisioningSessionId}/consumption-reporting-configuration` and the `post`operation. According to the YAML file the response headers shall contain a `Location` header pointing to the newly created consumption reporting configuration. 

It looks like our implementation is currently missing this `Location` header:

<img width="2107" alt="Bildschirmfoto 2024-04-26 um 09 41 28" src="https://github.com/5G-MAG/rt-5gms-application-function/assets/2427039/3db781c6-7538-464f-8989-d6b962dd9e65">

**Comment by rjb1000** [comment]
Agree that the `Location:` header is required to be present in the response to the _activateConsumptionReporting_ operation [per the YAML](https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-17/TS26512_M1_ConsumptionReportingProvisioning.yaml#L43-48).

If @davidjwbbc can reproduce, we should fix this little bug.
