### ISSUE TITLE
Implement M1 Content Protocols Discovery API

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#16]
# Design

This API provides the Application Provider with details of which downlink and uplink protocols are available for use with the 5GMS Application Function, and which geo-fencing locator types are available. The only method available with this API is `GET`.

Since our current implementation does not offer geo-fencing or uplink capabilities then the `uplinkEgestProtocols` and `geoFencingLocatorTypes` properties will not be present.

For `downlinkIngestProtocols` the only protocol we currently support is the pull ingest.

This means that for this API with our reference implementation the response is always a fixed JSON object:
```json
{
    "downlinkIngestProtocols": [
        {
            "termIdentifier": "urn:3gpp:5gms:content-protocol:http-pull-ingest",
            "descriptionLocator": "https://www.etsi.org/deliver/etsi_ts/126500_126599/126512/17.03.00_60/ts_126512v170300p.pdf#page=67"
        }
    ]
}
```

This JSON should form part of the source distribution as `ContentProtocolsDiscovery_body.json` and have a `ContentProtocolsDiscovery_body.h` file derived from it at build time which contains 3 `#define`'s:
1. The string for the file contents of the JSON file
2. A string containing the SHA256 hash hex string of the JSON file
3. A `time_t` value representing the modification time of the JSON file.

These can then be used in the `msaf-sm.c` where appropriate by including the `ContentProtocolsDiscovery_body.h` file.

The file contents are used as the body of the response. The SHA256 hash string is used as the `ETag` header value and the file modification `time_t` is formatted as the `Last-Modified` header value. The `Content-Type` is `application/json` and the `Cache-Control` and `Server` headers follow the rules set out in #37.

# Relevant specifications

- TS 26.512 clauses 4.3.4 and 7.5.

**Comment by devbbc** [comment]
Implemented M1 Content Protocols API. Sample Output:

```
$ curl -H 'User-Agent: AF' v http://127.0.0.22:7777/3gpp-m1/v2/provisioning-sessions/5518f5ba-ae8a-41ed-ab5e-53fa4058cd25/protocols
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> GET /3gpp-m1/v2/provisioning-sessions/5518f5ba-ae8a-41ed-ab5e-53fa4058cd25/protocols HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 282
< Cache-Control: max-age=86400
< Last-Modified: Fri, 17 Feb 2023 06:13:13 GMT
< ETag: ab39cc55ebe17acd46509cf3c6b891e7ee9a10576953a7989446fa209f7cfc39
< Content-Type: application/json
< Server: 5GMSdAF-af.localdomain/17.3.0 (info.title=M1_ContentProtocolsDiscovery; info.version=M1_ContentProtocolsDiscovery) rt-5gms-application-function/1.1.0
< Date: Fri, 17 Feb 2023 06:14:48 GMT
< 
{
    "downlinkIngestProtocols": [
        {
            "termIdentifier": "urn:3gpp:5gms:content-protocol:http-pull-ingest",
            "descriptionLocator": "https://www.etsi.org/deliver/etsi_ts/126500_126599/126512/17.03.00_60/ts_126512v170300p.pdf#page=67"
        }
    ]
}
```

**Comment by rjb1000** [comment]
Great, @devbbc. Just one small defect I noticed:

> (info.title=M1_ContentProtocolsDiscovery; info.version=M1_ContentProtocolsDiscovery)

Looks like`info.version` is being populated from the wrong macro, or something like that.

**Comment by devbbc** [comment]
Output generated with the correct macro for `info.version`

```
$ curl -H 'User-Agent: AF' v http://127.0.0.22:7777/3gpp-m1/v2/provisioning-sessions/d9d17c52-b13a-41ed-b530-25d08a1c40d8/protocols
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> GET /3gpp-m1/v2/provisioning-sessions/d9d17c52-b13a-41ed-b530-25d08a1c40d8/protocols HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 281
< Server: 5GMSdAF-af.localdomain/17.3.0 (info.title=M1_ContentProtocolsDiscovery; info.version=2.0.0) rt-5gms-application-function/1.2.0
< Cache-Control: max-age=86400
< Last-Modified: Mon, 20 Feb 2023 16:11:11 GMT
< ETag: ed726395231f818d2cb1aeb1a921f70d20e2a23ea50b57f9a7d2f4be82c01d31
< Content-Type: application/json
< Date: Mon, 20 Feb 2023 16:23:18 GMT
< 
{
    "downlinkIngestProtocols": [
        {
            "termIdentifier": "urn:3gpp:5gms:content-protocol:http-pull-ingest",
            "descriptionLocator": "https://www.etsi.org/deliver/etsi_ts/126500_126599/126512/17.03.00_60/ts_126512v170300p.pdf#page=67"
        }
    ]
}
```

**Comment by davidjwbbc** [comment]
Tested this and it looks good.

Pushed to development branch for release candidate in PR #53, closing this issue.
