### ISSUE TITLE
Uplift to TS 26.512 V17.9.0

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-function#163]
# Description
Version 17.9.0 of specification 3GPP TS 26.512 has recently been released. We will need to make some changes to the 5GMS AF in order to bring it in line with this new Release 17 specification version.

This release sees changes to 3 things which will affect the current Reference Tools 5GMS Application Function implementation:
1. The data type of the members of the metrics array are now _Uri_ rather than just a _string_.
2. Value ranges for _reportingInterval_ and _samplingPeriod_ are now declared in the YAML.
3. The _metricsReportingConfigurationId_ property, previously missing, is now always added to Service Access Information.

It has also been noticed that the _sliceScope_ property was added in v17.8.0 and will need to be included in this change.

# Work to be done

For the 3 changes detailed above:
1. Introduce the string validation regex matching (Issue #128) and then test that the Uri style regex match is applied to the metrics array.
2. The extra bounds for the _reportingInterval_ and _samplingPeriod_ properties should be picked up by the validation in the OpenAPI templates and so will just need the 5G_APIs version updating, then the code building and testing, no code changes should be required.
3. Some code will need to be added to copy the relevant _metricsReportingConfigurationId_ and _sliceScope_ (from v 17.8.0) values into the correct properties in the v17.9.0 ServiceAccessInformation structure. This will need implementing and testing and will then trigger changes in the 5G-MAG 5GMS Aware App once implemented (ack @dsilhavy).

Additionally:
- We have introduced, in the Data Collection, the ability to report the parameter a parse fails on. The 5GMS AF should use this to report back the parameter and reason in the ProblemDetail.

**Comment by stojkovicv** [comment]
In addition, 17.9 defines slightly different Metrics Reporting Configuration data model (clause 7.8.3.1). Do we want to include `sliceScope` with this uplift?

**Comment by rjb1000** [comment]
> In addition, V17.9.0 defines slightly different Metrics Reporting Configuration data model (clause 7.8.3.1). Do we want to include `sliceScope` with this uplift?

Good spot, @stojkovicv. I just checked, and *sliceScope* was actually added in V17.8.0, so this new parameter should have already been included in a previous uplift! So yes, let's include it in the scope of this issue. Please could you add it to the issue description, @davidjwbbc?

There is a knock-on effect: this parameter is also exposed in the *clientMetricsReportingConfigurations* object in Service Access Information at clause 11.2.3.1, so code will need to be written to copy it across from M1 to M5.

Other than that copying, I don't think the 5GMS internal logic changes in any way, so this should be simple to implement.

**Comment by davidjwbbc** [comment]
Implemented the basic uplift, only the additional passing back of error parameter names to be done now. This is a sizeable job as it touches every bit of API interface code and the error sending routine.

**Comment by davidjwbbc** [comment]
Implemented filling in of the *invalidParams* field in the ProblemDetails by adding the extra function parameter to pass back the field name where parse errors are happening. Also added a few URL path field *invalidParams* returns for when things like the `{provisioningSessionId}` from the URL path does not match an existing provisioning session.

Now I need to test everything to make sure it all still works as expected.

**Comment by davidjwbbc** [comment]
Uplift merged in PRs 5G-MAG/rt-common-shared#39, #164 and 5G-MAG/rt-5gms-application-provider#56
