### ISSUE TITLE
Remove inotify testing code from the Application Function

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#24]
# Specification

Some testing code was added to the Application Function in https://github.com/5G-MAG/rt-5gms-application-function/issues/7#issuecomment-1318207359 that detects deletion of a server certificate file in the local file system using the Linux `inotify` mechanism and uses that the provoke the M3 server certificate destruction operation.

Once the M1 server certificate destruction operation is implemented in #17, this testing code is redundant and should be removed.

**Comment by devbbc** [comment]
Removed functions and data structures introduced to facilitate Linux `inotify` mechanism.

**Comment by davidjwbbc** [comment]
Changes merged in PR #26
