### ISSUE TITLE
Error during building phase

### ISSUE THREAD

**Issue by stepski011** [5G-MAG/rt-5gms-application-function#27]
There is an issue during building application function on completely updated Ubuntu-based 22.04.1 LTS with command `ninja -C build` which returns those errors:
```
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
```
Attempts done and failed:

- To install `ninja-build` with `pip` instead of `apt`.
- Copying entire files from main ninja repository to desired location.
- Trying absolute path after `ninja -C`

Similar error with `ninja-build` has been discussed in other projects but without answer.

**Comment by devbbc** [comment]
Looks like there is no `build` directory in `rt-5gms-application-function`.  Please run `meson build --prefix=`pwd`/install` from `rt-5gms-application-function` directory and then execute `ninja -C build`.

Before executing the above steps, it is advisable to remove the `build` directory if it already exists.

**Comment by stepski011** [comment]
Using Linux on Virtual box is causing this annoying issue. Installation breaks despite existing `build` folder. The reason is because ` meson build --prefix=`pwd`/install ` is not executing fully and report errors. 
However no issues on native Linux computer.

**Comment by rjb1000** [comment]
Does the problem on VirtualBox still need looking into, @stepski011, or can this issue be resolved?

**Comment by stepski011** [comment]
The issue can be resolved.
