### ISSUE TITLE
ServiceAccessInformation.streamingAccess.mediaPlayerEntry should use ContentHostingConfiguration.distributionConfigurations.domainNameAlias as the authority name when present.

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-function#28]
**Describe the bug**
If the Application Function is configured with a `ContentHostingConfiguration` which specifies `distributionConfigurations.domainNameAlias`, the alias name should be used in the `ServiceAccessInformation.streamingAccess.mediaPlayerEntry` URL as the authority in preference to the `canonicalDomainName`.

**To Reproduce**
1. Configure a `ContentHostingConfiguration` which uses `domainNameAlias` in its distributionConfigurations.
2. Run the Application Function.
3. Fetch the Service Access Information
4. Observe that the `mediaPlayerEntry` URL references the `canonicalDomainName` of the Application Server instead of the provided `domainNameAlias`.

**Expected behavior**
The `mediaPlayerEntry` URL authority should be the same as the `domainNameAlias`.

**Desktop:**
 - OS: Ubuntu 22.04.1
 - Browser: curl

**Comment by rjb1000** [comment]
@davidjwbbc: Does this also impact the existing MVP#2 release of the 5GMS AF?

**Comment by davidjwbbc** [comment]
Yes it will, I'll add it to that project too.

**Comment by davidjwbbc** [comment]
If we fix this on the development branch it can be backported to the v1.0.x branch.

**Comment by davidjwbbc** [comment]
Back porting this to MVP#2 v1.0.x branch

**Comment by davidjwbbc** [comment]
Released a while ago as tested an working
