### ISSUE TITLE
Enhancement: Return the number of purged cache entries to the M1 client

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-function#36]
# Context
We would like to return the number of cache entries purged to the M1 client.

The M3 interface is also being updated to return the number of cache entries in 5G-MAG/rt-5gms-application-server#56.

# Enhancement specification
The AF shall respond with:
- _204 (No Content)_ if the request was valid but no cache entries were purged (none matched the request),
- _200 (OK)_ if one or more cache entries were purged, with the body being a single integer indicating the aggregate number of entries purged from all Application Servers used for the Provisioning Session in the M1 response once the purge is complete.

**Comment by devbbc** [comment]
Implemented the capabilities to return the aggregate number of entries purged from all Application Servers. Need to test it with latest version of the Application Server and possibly some tweaks required based on the testing.

**Comment by davidjwbbc** [comment]
Tested and this looks good.

Pushed to development branch for release candidate in PR #53, closing this issue.
