### ISSUE TITLE
Expose list of current 5GMS Provisioning Sessions

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#41]
_This feature is not currently standardised in TS 26.512._

# Context

To assist users of the reference 5GMS AF implementation, it would be useful to expose a list of Provisioning Sessions currently available.

This information may, for example, be used to populate a management user interface that goes on to retrieve the Provisioning Session resource for each item in the list.

# Specification

When a `GET` request is made to the Provisioning Sessions collection at the path `/5gmag-rt-management/v1/provisioning-sessions` the response shall be a JSON document containing a simple array of Provisioning Session IDs.

For example:
```
["4fbe09f3-a571-4c34-b9f4-6fc9795ce589", "07701f2a-c339-4d76-b5bf-fb0f6289a845", "05f06520-bb36-4aab-b444-5c78ce3f7c4b"]
```
Because this is a response to a non-standard request, the `Server` header shall _not_ include the comment indicating the API name and version. But the product identifier and subproduct identifier shall still be present as normal.

# Additional information
In this first implementation, all Provisioning Sessions are included in the response message.

In a future implementation of the 5GMS AF that supports OAuth-based authentication, only the subset of Provisioning Sessions associated with the authorised Application ID should be included in the response.

There is no requirement to expose a list of Provisioning Session IDs at reference points M1 or M5.

**Comment by davidjwbbc** [comment]
Having thought about this I'm not really sure how useful this would actually be.

In order to configure the Application Function the Application Provider would use the M1 interface. As part of that interaction it would be passed the Provisioning Session Ids, Certificates Ids, etc. which it would remember. As part of its operations the AP would be the one to publish the list of Provisioning Session Ids to its 5GMS Aware Application(s). Since it's the AP responsible for publishing there is no need for this to be available from the interface at M1.

The only use at M1 would be for an AP that has failed to maintain persistent state information or possibly for an admin to summarise the current AF configuration.

So for the reference implementation the Reference M1 Client would maintain a persistent database of relevant Ids and this is what would be used to publish the list of available Provisioning Session Ids.

**Comment by rjb1000** [comment]
Yes, you're right @davidjwbbc that an M1 client will likely already know which Provisioning Sessions it has provisioned at M1.

The Use Case I am trying to support with this is an independent party wishing to query which Provisioning Sessions it has visibility of. This could be a web-based inspector, for example.

> So for the reference implementation the Reference M1 Client would maintain a persistent database of relevant Ids and this is what would be used to publish the list of available Provisioning Session Ids.

Just to note that we don't currently have any plans to develop a reference M1 client with a persistent database. (There is no 3GPP specification for an M1 client application with data persistence, hence no reference implementation is possible.) The extent of our current ambitions is to provide a set of client-side Python classes that would enable such an application to be developed by someone.

**Comment by rjb1000** [comment]
@davidjwbbc has separately made an argument to expose this via a new implementation-specific management API, to maintain the purity of the M1 Provisioning Sessions API. This seems like a reasonable suggestion. I'll sleep on it and maybe revise the specification.

**Comment by rjb1000** [comment]
> @davidjwbbc has separately made an argument to expose this via a new implementation-specific management API, to maintain the purity of the M1 Provisioning Sessions API. This seems like a reasonable suggestion. I'll sleep on it and maybe revise the specification.

I have revised per @davidjwbbc's above suggestion and have proposed a candidate YAML API in Pull Request 5G-MAG/rt-common-shared#19.

**Comment by devbbc** [comment]
Implemented the management API to get the list of Provisioning Sessions as shown in the below sample output:

```
$ curl -H 'User-Agent: AF' v http://127.0.0.22:7777/5gmag-rt-management/v1/provisioning-sessions/
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> GET /5gmag-rt-management/v1/provisioning-sessions HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 80
< Cache-Control: max-age=62
< Content-Type: application/json
< Server: 5GMSdAF-af.localdomain/17 rt-5gms-application-function/1.2.0
< Date: Mon, 27 Feb 2023 18:14:34 GMT
< 
* Connection #0 to host 127.0.0.22 left intact
["946ec1ac-b6ca-41ed-9ef8-4310a1516408", "954b0ac2-b6ca-41ed-9ef8-4310a1516408"]
```

This Management interface can uses the same network address as the M1 interface. Next step is to explore possibility to run the management interface over another network address. This requires modifying the  MSAF configuration file to specify the IP address for the management interface and listening to that address for requests.

**Comment by devbbc** [comment]
The network configurations for the M1 management interface can now be set through the configuration file `msaf.yaml` . The configuration parameters are same as that of the sbi interface, but targeted for the management operations. A sample configuration:

```
...
m1ManagementInterface:
        - addr: 127.0.0.23
          port: 7777
...
``` 

With this configuration, the Application Function is modified to run two servers as shown below:

```
03/01 18:04:42.530: [sbi] INFO: mhd_server() [127.0.0.22]:7777 (../subprojects/open5gs/lib/sbi/mhd-server.c:279)
03/01 18:04:42.530: [sbi] INFO: mhd_server() [127.0.0.23]:7777 (../subprojects/open5gs/lib/sbi/mhd-server.c:279)

```

With this setup, we can have a separate state machine for the  management operations. Next step is to implement this state machine.

**Comment by rjb1000** [comment]
Is this work complete now, @devbbc?

**Comment by devbbc** [comment]
M1 Management interface now has its own state machine. This isolates this interface from the rest of the M1 Provisioning Sessions APIs.

- If the management interface is present

 The enumerated list of Provisioning Sessions can only be retrieved through the management interface. 
 Acessing the enumerated list of Provisioning Sessions through the M1 Provisioning Sessions APIs is forbidden.

When the M1 Management interface is not configured, the enumerated list of Provisioning Sessions can be retrieved through the M1 Provisioning Sessions APIs. 

Sample test:

Instantiate the AF with two interfaces

```
3/06 16:19:51.981: [app] INFO: Configuration: 'msaf.yaml' (../subprojects/open5gs/lib/app/ogs-init.c:126)
03/06 16:19:51.983: [sock] DEBUG: addr:127.0.0.22, port:7777 (../subprojects/open5gs/lib/core/ogs-sockaddr.c:140)
03/06 16:19:51.983: [sock] DEBUG: addr:127.0.0.23, port:7777 (../subprojects/open5gs/lib/core/ogs-sockaddr.c:140)

```
Here, 127.0.0.23 is the management interface.

Let's create two provisioning sessions through the M1 Provisioning API:

```
$ curl -H 'User-Agent: AF' -H 'Content-Type' --DATA @/home/ubuntu/ps.json -v http://127.0.0.22:7777/3gpp-m1/v2/provisioning-sessions/q
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> POST /3gpp-m1/v2/provisioning-sessions/q HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> Content-Length: 118
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 118 out of 118 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Connection: Keep-Alive
< Content-Length: 179
< Content-Type: application/json
< Location: /3gpp-m1/v2/provisioning-sessions/q/c40a808e-bc3a-41ed-966e-830b623c2028
< Server: 5GMSdAF-af.localdomain/17 (info.title=M1_ProvisioningSessions; info.version=2.0.0) rt-5gms-application-function/1.2.0
< Cache-Control: max-age=62
< Last-Modified: Mon, 06 Mar 2023 16:20:10 GMT
< ETag: c36a278e726bbee52e514459bb9287b65f87fc64c2028c3ca2a1ea45d3653991
< Date: Mon, 06 Mar 2023 16:20:10 GMT
< 
{
	"provisioningSessionId":	"c40a808e-bc3a-41ed-966e-830b623c2028",
	"provisioningSessionType":	"DOWNLINK",
	"aspId":	"BBC",
	"externalApplicationId":	"Media Streaming Downlink"
* Connection #0 to host 127.0.0.22 left intact
}
```
```
$ curl -H 'User-Agent: AF' -H 'Content-Type' --DATA @/home/ubuntu/ps.json -v http://127.0.0.22:7777/3gpp-m1/v2/provisioning-sessions/q
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> POST /3gpp-m1/v2/provisioning-sessions/q HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> Content-Length: 118
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 118 out of 118 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Connection: Keep-Alive
< Content-Length: 179
< Content-Type: application/json
< Location: /3gpp-m1/v2/provisioning-sessions/q/c6a3e628-bc3a-41ed-966e-830b623c2028
< Server: 5GMSdAF-af.localdomain/17 (info.title=M1_ProvisioningSessions; info.version=2.0.0) rt-5gms-application-function/1.2.0
< Cache-Control: max-age=62
< Last-Modified: Mon, 06 Mar 2023 16:20:14 GMT
< ETag: 18975f2794186f355cba679f37e9279db059652b1eaec7b0111b20c33465acde
< Date: Mon, 06 Mar 2023 16:20:14 GMT
< 
{
	"provisioningSessionId":	"c6a3e628-bc3a-41ed-966e-830b623c2028",
	"provisioningSessionType":	"DOWNLINK",
	"aspId":	"BBC",
	"externalApplicationId":	"Media Streaming Downlink"
* Connection #0 to host 127.0.0.22 left intact
}
```
To get the current list of provisioning sessions:

```
$ curl -H 'User-Agent: AF' -v http://127.0.0.23:7777/5gmag-rt-management/v1/provisioning-sessions/
*   Trying 127.0.0.23:7777...
* TCP_NODELAY set
* Connected to 127.0.0.23 (127.0.0.23) port 7777 (#0)
> GET /5gmag-rt-management/v1/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.23:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 80
< Cache-Control: max-age=62
< Content-Type: application/json
< Server: 5GMSdAF-af.localdomain/17 rt-5gms-application-function/1.2.0
< Date: Mon, 06 Mar 2023 16:20:36 GMT
< 
* Connection #0 to host 127.0.0.23 left intact
["c40a808e-bc3a-41ed-966e-830b623c2028", "c6a3e628-bc3a-41ed-966e-830b623c2028"]
```
Trying to `5gmag-rt-management/v1/provisioning-sessions` through the other interfaces is forbidden as shown in the sample belowL

```
$ curl -H 'User-Agent: AF' -v http://127.0.0.22:7777/5gmag-rt-management/v1/provisioning-sessions
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> GET /5gmag-rt-management/v1/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Connection: Keep-Alive
< Content-Length: 149
< Content-Type: application/problem+json
< Server: 5GMSdAF-af.localdomain/17 rt-5gms-application-function/1.2.0
< Date: Mon, 06 Mar 2023 16:20:46 GMT
< 
{
	"title":	"Forbidden resource",
	"status":	403,
	"detail":	"Cannot access the resource through this network, use the management network instead."
* Connection #0 to host 127.0.0.22 left intact
}
```
On the other hand, no other operations related to provisioning sessions can be performed through the management interface. For example, trying to create a provisioning session through the M1 management fails as shown below:

```
$ curl -H 'User-Agent: AF' -H 'Content-Type' --DATA @/home/ubuntu/ps.json -v http://127.0.0.23:7777/3gpp-m1/v2/provisioning-sessions/
*   Trying 127.0.0.23:7777...
* TCP_NODELAY set
* Connected to 127.0.0.23 (127.0.0.23) port 7777 (#0)
> POST /3gpp-m1/v2/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.23:7777
> Accept: */*
> User-Agent: AF
> Content-Length: 118
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 118 out of 118 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Connection: Keep-Alive
< Content-Length: 134
< Content-Type: application/problem+json
< Server: 5GMSdAF-af.localdomain/17 rt-5gms-application-function/1.2.0
< Date: Mon, 06 Mar 2023 16:22:59 GMT
< 
{
	"type":	"/3gpp-m1/v2",
	"title":	"Invalid API name.",
	"status":	400,
	"detail":	"3gpp-m1",
	"instance":	"/provisioning-sessions"
* Connection #0 to host 127.0.0.23 left intact
}

```
- If the management interface is not present

Now, I instantiate the AF without the M1 Management Interface:

```
03/06 16:30:10.202: [app] INFO: Configuration: 'msaf.yaml' (../subprojects/open5gs/lib/app/ogs-init.c:126)
03/06 16:30:10.203: [sock] DEBUG: addr:127.0.0.22, port:7777 (../subprojects/open5gs/lib/core/ogs-sockaddr.c:140)
```
In this case, the current list of provisioning sessions can be obtained:

```
$curl -H 'User-Agent: AF' -v http://127.0.0.22:7777/5gmag-rt-management/v1/provisioning-sessions/
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> GET /5gmag-rt-management/v1/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 80
< Cache-Control: max-age=62
< Content-Type: application/json
< Server: 5GMSdAF-af.localdomain/17 rt-5gms-application-function/1.2.0
< Date: Mon, 06 Mar 2023 16:32:22 GMT
< 
* Connection #0 to host 127.0.0.22 left intact
["64896c36-bc3c-41ed-9690-81a59333f924", "6ff901da-bc3c-41ed-9690-81a59333f924"]
```

**Comment by rjb1000** [comment]
Very good, @devbbc. Although your examples need checking: I spotted a few mistakes in the request URLs.

I'm not so keen on the following behaviour:

> When the M1 Management interface is not configured, the enumerated list of Provisioning Sessions can be retrieved through the M1 Provisioning Sessions APIs.

I think this should not be supported because it mixes a non-standard behaviour onto a standardised API.

**Comment by davidjwbbc** [comment]
> Very good, @devbbc. Although your examples need checking: I spotted a few mistakes in the request URLs.
> 
> I'm not so keen on the following behaviour:
> 
> > When the M1 Management interface is not configured, the enumerated list of Provisioning Sessions can be retrieved through the M1 Provisioning Sessions APIs.
> 
> I think this should not be supported because it mixes a non-standard behaviour onto a standardised API.

I think it's fine because M1 and M5 are already mixed on this listening address. All three interfaces have different prefixes keeping them separate even on the same listening address:
- M1 - `/3gpp-m1/v2`
- M5 - `/3gpp-m5/v2`
- Maf - `/5gmag-rt-management/v1`

**Comment by rjb1000** [comment]
It's news to me that M5 was on the same listening port as M1. This is definitely not what is wanted!

Now that we have learned how to instantiate multiple different listening ports, we should separate M5 onto a different one from M1.

What we need is three separate endpoint address specifications in `msaf.yaml`:
- `m1` for M1 Provisioning APIs.
- `m5` for M5 Media Session Handling APIs.
- `maf` for Maf Management APIs.

**Comment by rjb1000** [comment]
A couple of remedials discussed today:
* Return 404 (Not Found) instead of 403 (Forbidden) or 400 (Bad Request) when the URL is not valid on the endpoint addressed by the client.
* Provisioning Sessions API needs to have better request URL validation.

**Comment by devbbc** [comment]
The remedials mentioned above are addressed:

# Return 404 (Not Found) instead of 403 (Forbidden)  

Trying to  access `5gmag-rt-management/v1/provisioning-sessions` through the M1/M5 endpoint address (127.0.0.22) returns 404 (Not Found) instead of 403 (Forbidden)  as shown in the sample below:

```
$ curl -H 'User-Agent: AF' -v http://127.0.0.22:7777/5gmag-rt-management/v1/provisioning-sessions/
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> GET /5gmag-rt-management/v1/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Connection: Keep-Alive
< Content-Length: 124
< Content-Type: application/problem+json
< Server: 5GMSdAF-af.localdomain/17 (info.title=Maf_Management; info.version=1.0.0) rt-5gms-application-function/1.2.0
< Date: Wed, 08 Mar 2023 14:16:20 GMT
< 
{
	"title":	"Not Found",
	"status":	404,
	"detail":	"Resource [/5gmag-rt-management/v1/provisioning-sessions/] not found."
* Connection #0 to host 127.0.0.22 left intact

```
# Return 400 (Bad Request) for the invalid URL on the endpoint addressed by the client.

When the  the endpoint addressed by the client is not a valid URL, response with 404 (Bad Request) is returned.


```
$ curl -H 'User-Agent: AF' -H 'Content-Type' --DATA @/home/ubuntu/ps.json -v http://127.0.0.23:7777/3gpp-m1/v2/provisioning-sessions/
*   Trying 127.0.0.23:7777...
* TCP_NODELAY set
* Connected to 127.0.0.23 (127.0.0.23) port 7777 (#0)
> POST /3gpp-m1/v2/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.23:7777
> Accept: */*
> User-Agent: AF
> Content-Length: 118
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 118 out of 118 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Connection: Keep-Alive
< Content-Length: 129
< Server: 5GMSdAF-af.localdomain/17 (info.title=Maf_Management; info.version=1.0.0) rt-5gms-application-function/1.2.0
< Content-Type: application/problem+json
< Date: Wed, 08 Mar 2023 14:19:49 GMT
< 
{
	"type":	"/3gpp-m1/v2",
	"title":	"Bad Request.",
	"status":	400,
	"detail":	"3gpp-m1",
	"instance":	"/provisioning-sessions"
* Connection #0 to host 127.0.0.23 left intact
```

# Better URL Validation for Provisioning Sessions API

Added additional checks for URL validation. For example, `POST` request with a valid URL, results in successful response as shown below:

```
curl -H 'User-Agent: AF' -H 'Content-Type' --DATA @/home/ubuntu/ps.json -v http://127.0.0.22:7777/3gpp-m1/v2/provisioning-sessions/
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> POST /3gpp-m1/v2/provisioning-sessions/ HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> Content-Length: 118
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 118 out of 118 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Connection: Keep-Alive
< Content-Length: 179
< Content-Type: application/json
< Location: /3gpp-m1/v2/provisioning-sessions/347c067a-bdbd-41ed-a297-11bd67bca93c
< Server: 5GMSdAF-af.localdomain/17 (info.title=M1_ProvisioningSessions; info.version=2.0.0) rt-5gms-application-function/1.2.0
< Cache-Control: max-age=62
< Last-Modified: Wed, 08 Mar 2023 14:26:24 GMT
< ETag: 7deef4012e4c9ab2d1c3d667a5d343e2aedcd8758a83c1ed7850bed1d2813198
< Date: Wed, 08 Mar 2023 14:26:24 GMT
< 
{
	"provisioningSessionId":	"347c067a-bdbd-41ed-a297-11bd67bca93c",
	"provisioningSessionType":	"DOWNLINK",
	"aspId":	"BBC",
	"externalApplicationId":	"Media Streaming Downlink"
* Connection #0 to host 127.0.0.22 left intact
}
``'

An additional path component, makes the URL invalid  triggering an error:

```
$ curl -H 'User-Agent: AF' -H 'Content-Type' --DATA @/home/ubuntu/ps.json -v http://127.0.0.22:7777/3gpp-m1/v2/provisioning-sessions/xy
*   Trying 127.0.0.22:7777...
* TCP_NODELAY set
* Connected to 127.0.0.22 (127.0.0.22) port 7777 (#0)
> POST /3gpp-m1/v2/provisioning-sessions/xy HTTP/1.1
> Host: 127.0.0.22:7777
> Accept: */*
> User-Agent: AF
> Content-Length: 118
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 118 out of 118 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Connection: Keep-Alive
< Content-Length: 190
< Content-Type: application/problem+json
< Server: 5GMSdAF-af.localdomain/17 (info.title=M1_ProvisioningSessions; info.version=2.0.0) rt-5gms-application-function/1.2.0
< Date: Wed, 08 Mar 2023 14:26:34 GMT
< 
{
	"type":	"/3gpp-m1/v2",
	"title":	"Provisioning session does not exist.",
	"status":	404,
	"detail":	"Provisioning session [xy] does not exist.",
	"instance":	"/provisioning-sessions/xy"
* Connection #0 to host 127.0.0.22 left intact
}
```

**Comment by rjb1000** [comment]
Is this one tested and complete, @davidjwbbc?

**Comment by davidjwbbc** [comment]
Tested and observed memory leaks removed in the v1.3.0 release candidate. I'll close this issue now.
