### ISSUE TITLE
Issues when Testing the M5 Interface

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/rt-5gms-application-function#47]
Just a very minor comment. 
In the documentation, when testing with a bogus provisioning session id, the line says:

> Using a bogus provisioning session id, perform a GET request on the interface URL.
> Example command if the provisioning session id is 0c5cc9e6-a6dd-41ed-ae90-e781c44d0f0c:

It should say, for instance:
> Using a bogus provisioning session id, perform a GET request on the interface URL.
> Example command if the provisioning session id is `does-not-exist`

On another note:
I get always (for any test case) an HTTP message "Mark bundle as not supporting multiuse" which is not reported in the example given in the documentation. Just wondering if I'm doing something different:
```
*   Trying 127.0.0.1:7778...
* Connected to 127.0.0.1 (127.0.0.1) port 7778 (#0)
> GET /3gpp-m5/v2/service-access-information/does-not-exist HTTP/1.1
> Host: 127.0.0.1:7778
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 15 Feb 2023 08:02:40 GMT

```

**Comment by rjb1000** [comment]
> * Mark bundle as not supporting multiuse

Looks like all the lines beginning with an asterisk are a running commentary of HTTP client library internals. I'm not sure it's worth including these in the documentation. But there could be a general note saying "Additional lines beginning with an asterisk will also appear in the output providing information about internal operation of the test client."

**Comment by jordijoangimenez** [comment]
Agree. If not a critical/warning message, we could leave it out not to confuse. Let's add that line.

**Comment by davidjwbbc** [comment]
Ok, I've addressed those two in the [Testing the M5 Interface](https://github.com/5G-MAG/rt-5gms-application-function/wiki/Testing-the-M5-Interface) wiki page.

**Comment by jordijoangimenez** [comment]
Excellent. I believe we can close.
