### ISSUE TITLE
Issues when testing M1 Interface

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/rt-5gms-application-function#57]
When Testing as a Local User, this command `~/rt-5gms-application-function/install/bin/m1-session configure set data_store ~/m1-client-data-store` produces the following error:
```
Traceback (most recent call last):
  File "/home/fivegmag/rt-5gms-application-function/install/bin/m1-session", line 96, in <module>
    from rt_m1_client.session import M1Session
ModuleNotFoundError: No module named 'rt_m1_client'
```
The same error pops up when "creating a Single Provisioning Session" (`~/rt-5gms-application-function/install/bin/m1-session new-provisioning-session -e MyAppId -a MyASPId
`)

**Comment by davidjwbbc** [comment]
You need to follow the instructions from the ["Running" section of the Testing as a Local User](https://github.com/5G-MAG/rt-5gms-application-function/wiki/Testing-as-a-Local-User#running) wiki page. The important part is the bit about setting the `PYTHONPATH` environment variable.

**Comment by jordijoangimenez** [comment]
This issue was resolved by: `PYTHONPATH=`find ~/rt-5gms-application-function/install -type d '(' -name 'site-packages' -o -name 'dist-packages' ')' -print` export PYTHONPATH`

as for some distributions the folder is site-packages or dist-packages. More info: https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages
