### ISSUE TITLE
Uplift to latest Open5GS

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-application-function#60]
# Description

The current version of Open5GS used in the 5GMS Application Function uses Release 16 specifications of the 5G core APIs. The latest version of Open5GS has been updated to the newer Release 17 APIs.

Since we are starting on some work (Network Assistance and Dynamic Policies) that will see closer integration with the 5G Core network functions, this would be a good opportunity to resynchronise the Open5GS version being used.

This issue is here to track the work to uplift the 5GMS Application Function to work with the latest version of Open5GS.

This will require changing the open5gs repository commit we use and changing our scripts to use a new version of the openapi-generator (to match the version in use by open5gs) and to look for the open5gs openapi-generator configuration and templates in their new location in the repository.

The 5GMS Application Function should then be fully tested to ensure it still works with the new generated API models and open5gs libraries.

**Comment by rjb1000** [comment]
It would be good to record on this issue the version numbers of _Open5GS_ and _OpenAPI Generator_ selected as baseline.

**Comment by davidjwbbc** [comment]
Open5GS is at v2.6.2 and uses openapi-generator v6.4.0

**Comment by devbbc** [comment]
Tested the functionality of the newly built AF and it works as it should.

The SBI library of the latest version of Open5GS checks if TLS is enabled or not. For this purpose, it expects a flag in the configuration file `msaf.yaml`:

```
sbi:
    server:
      no_tls: true
     
    client:
      no_tls: true
```

If `no_tls: true` is not in the configuration, the AF fails while communicating with the AS over the M3 link as the [OGS SBI client expects a key for the client.
](open5gs/open5gs/blob/bc3b27339e159c07c8c6397fe0707461dbb3bb77/lib/sbi/client.c#L388)
