### ISSUE TITLE
Implement Metrics Reporting Provisioning API at reference point M1

### ISSUE THREAD

**Issue by stojkovicv** [5G-MAG/rt-5gms-application-function#68]
# Associated specifications
TS 26.512 (17.4.0) defines this API in *7.8*, it's procedures in clause *4.3.9*.

# Specification
Role of this API is to configure and to control Metrics Reporting feature on M1 interface and to implement main procedures for Metrics Reporting Configuration which includes generating its related unique identifier (UUID). It allows Application Provider to configure the Metrics Collection and Reporting procedure for a particular downlik or uplink media streaming.
The scope of issue is comprising following methods:

## Create: `msaf_metrics_reporting_configuration_create`
Method creates new resource for particular provisioning session. It is possible to have multiple configuration resources within one provisioning session which are separated with unique identifier (UUID).
Method has been invoked with `POST` request from Application provider. If creation was successful the `201 (Created)` shall be response from AF, and the URL of the created resource is returned in the `Location` header of the response.

Related endpoint: `/3gpp-m1/v2/provisioning-sessions/{provisioningSessionId}/metrics-reporting-configurations`

## Read:
This procedure allows retrieval of Metrics Reporting Configuration properties. Simple `GET` request from Application provider side will show configuration properties in JSON format for certain UUID. In case of success, the response is `200 (OK)` and the particular configuration properties has been listed.

Related endpoint: `/3gpp-m1/v2/provisioning-sessions/{provisioningSessionId}/metrics-reporting-configurations/{metricsReportingConfigurationId}`

## Update:
When this method is triggered, the Metrics Reporting Configuration resource is either initially uploaded, entirely replaced or just modified. It's possible to update all available configuration properties.
Procedure is runned with `PUT` request and response is `200 (OK)` in case of successful update.

Related endpoint: `/3gpp-m1/v2/provisioning-sessions/{provisioningSessionId}/metrics-reporting-configurations/{metricsReportingConfigurationId}` 

## Destroy:
This method removes Metrics Reporting Configuration taking its UUID as an argument in the request. AF receive `DELETE` request and response with `200` if the resource has been successfully deleted.

Related endpoint: `/3gpp-m1/v2/provisioning-sessions/{provisioningSessionId}/metrics-reporting-configurations/{metricsReportingConfigurationId}`

### TBD
Further clarification is needed in case that each of stated procedure fails. According to the specification, all errors repsones are defined in clause *6.3.*, however not clear enough.
*Solution*: Existing implementation for other features will serve as a template for cover tin error responses.

### To be clarified
Looking at the code of procedure to create `Provisioning Session` on M1, it invokes method from external OpenAPI model (imported in related header file) named `OpenAPI_provisioning_session_create()`. This method is part of `provisioning-session.c` within `src/5gmsaf/openapi/models/`. Is the same logic applicable to Metrics Reporting Provisioning API and it's procedure to Create Metrics Reporting Configuration?

The only OpenAPI model which make sense to be related to Metrics reporting feature is called `service_access_information_resource_client_metrics_reporting_configuration.c` within the same location as previous model.
It indeed have defined method called `OpenAPI_service_access_information_resource_client_metrics_reporting_configuration_create()`, but the name suggest that it's operate with Service Access Information Client.

**Comment by rjb1000** [comment]
Hi @stepski011. As a simplification, you might want to leave the `PATCH` method of the *Update operation* until the end. It's quite complex to implement, and not well enough specified in TS 26.512 in my opinion.

We have skipped that for our reference implementation Content Hosting Configuration. Complete replacement of a Metrics Reporting Configuration using `PUT` is probably adequate for most usages.

**Comment by rjb1000** [comment]
> Looking at the code of procedure to create Provisioning Session on M1, it invokes method from external OpenAPI model (imported in related header file) named OpenAPI_provisioning_session_create(). This method is part of provisioning-session.c within src/5gmsaf/openapi/models/. Is the same logic applicable to Metrics Reporting Provisioning API and it's procedure to Create Metrics Reporting Configuration?
>
> The only OpenAPI model which make sense to be related to Metrics reporting feature is called service_access_information_resource_client_metrics_reporting_configuration.c within the same location as previous model.
It indeed have defined method called OpenAPI_service_access_information_resource_client_metrics_reporting_configuration_create(), but the name suggest that it's operate with Service Access Information Client.

Suggest you get in touch with @davidjwbbc straight away on this point.

Provisioning Session is the umbrella resource. Each Metrics Reporting Configuration sits under this as a subresource and has its own data models, similar to the way a Content Hosting Configuration also sits under a Provisioning Session umbrella.

I suspect therefore that you're missing a data model corresponding to the `MetricsReportingConfiguration` data type defined in the `M1_MetricsReportingProvisioning.yaml` file.

Using the M5 Service Access Information data model doesn't sound right to me.

**Comment by davidjwbbc** [comment]
> > Looking at the code of procedure to create Provisioning Session on M1, it invokes method from external OpenAPI model (imported in related header file) named OpenAPI_provisioning_session_create(). This method is part of provisioning-session.c within src/5gmsaf/openapi/models/. Is the same logic applicable to Metrics Reporting Provisioning API and it's procedure to Create Metrics Reporting Configuration?
> > The only OpenAPI model which make sense to be related to Metrics reporting feature is called service_access_information_resource_client_metrics_reporting_configuration.c within the same location as previous model.
> > It indeed have defined method called OpenAPI_service_access_information_resource_client_metrics_reporting_configuration_create(), but the name suggest that it's operate with Service Access Information Client.
> 
> Suggest you get in touch with @davidjwbbc straight away on this point.
> 
> Provisioning Session is the umbrella resource. Each Metrics Reporting Configuration sits under this as a subresource and has its own data models, similar to the way a Content Hosting Configuration also sits under a Provisioning Session umbrella.
> 
> I suspect therefore that you're missing a data model corresponding to the `MetricsReportingConfiguration` data type defined in the `M1_MetricsReportingProvisioning.yaml` file.
> 
> Using the M5 Service Access Information data model doesn't sound right to me.

To include another OpenAPI YAML file model you need to add the filename to the list in the `default_apis` variable in `src/5gmsaf/generator-5gmsaf`, i.e. add "` TS26512_M1_MetricsReportingProvisioning`" to that variable.

Then run the `src/5gmsaf/generator-5gmsaf` script to regenerate the OpenAPI bindings and the new component schemas from that YAML file will be added to the `src/5gmsaf/openapi/model/` directory.

**Comment by davidjwbbc** [comment]
> Hi @stepski011. As a simplification, you might want to leave the `PATCH` method of the _Update operation_ until the end. It's quite complex to implement, and not well enough specified in TS 26.512 in my opinion.
> 
> We have skipped that for our reference implementation Content Hosting Configuration. Complete replacement of a Metrics Reporting Configuration using `PUT` is probably adequate for most usages.

Yes, I'd suggest you ignore `PATCH` for now and just implement `PUT`.

`PATCH` requires some sort of introspection on the model which is not catered for in the current openapi-generator templates. This means it could be a lot of work to implement.

Although it had crossed my mind as to whether we could, in order to implement `PATCH`, convert the object to a JSON string, and then run that JSON string though a generic JSON patch library function(s) and convert the resulting JSON string back to an object of the relevant type. That way introspection would not be needed. But let's leave that for another time.

**Comment by stojkovicv** [comment]
Current update is related to the creation procedure and certificate mapping concept. It has been clarified how MRC (Metrics Reporting Configuration) data model has been generated.
Looking at the code for CHC (Content Hosting Configuration) procedures within the Provisioning Session API, lead me to the certificate mapping concept. The way I understood it: `certificate_map` is created for Provisioning session, each `distributionConfiguration` within the CHC is assigned own `certificate_id` and mapped to corresponding certificate data (coming via M1 interface). Further functions are checking and validating existence of `certificate_id`, retrieving the `filename` etc. Finally, more functions are handling hashing of provisioning session and service access information.

From perspective of mapping concept, key difference between CRC and MRC, is that CRC data model have special field called `distributionConfigurations` of type `array(Object)`, which require more processing (more than one distribution may be configured for one CHC). Consequently, certain mapping functions will be modified while other has to be freshly implemented to manage MRC certificate.

For now, the main focus remains at correct understanding of MRC mapping.

**Comment by rjb1000** [comment]
@stojkovicv: The Metrics Reporting feature is considerably simpler than the Content Hosting feature. You don't need to worry about Server Certificates at all because these are only relevant to the client-facing interface of the 5GMS AS for serving hosted media content (i.e. reference point M4) and the 5GMS AS doesn't play any role in Metrics Reporting.

As @davidjwbbc has laid out above, all the complexity for Server Certificates provisioning and Content Hosting provisioning is already implemented. The delta to add Metrics Reporting provisioning is just his step 3. And then there are some downstream additions at steps 4 and 6 to expose this in Service Access Information at reference point M5. Plus a client-side change to the Media Session Handler in step 5.

**Comment by stojkovicv** [comment]
In order to test the changes that I've done on M1 regarding this API, there are few steps to be done, and I would appreciate your comments on that. Namely, `meson` and `ninja` are used to compile AF code, and to build this component in Linux system. Since all the programming is happening locally, I must be able to compile AF with my changes, probably using same commands as during installation. What is the proper way to compile and debug AF after new implementations?

**Comment by davidjwbbc** [comment]
Building is the same as per the [instructions on the AF wiki](https://github.com/5G-MAG/rt-5gms-application-function/wiki/Testing-as-a-Local-User). You'll need to do the *Building*, *Installing* and *Configuring* steps from that page. I take a copy of the `install/etc/open5gs/msaf.yaml` file as `local-msaf.yaml` and change the logging to debug level (see the [suggested logging configurations](https://github.com/5G-MAG/rt-5gms-application-function/wiki/Configuring-the-Application-Function#suggested-logging-configurations) on the configuration wiki page). When it comes to running I use `gdb` so that if (when) the AF aborts or generates a segment fault you can examine the back trace and local variables, e.g.:
```bash
gdb --args install/bin/open5gs-msafd -c local-msaf.yaml
gdb> run
```

**Comment by stojkovicv** [comment]
There's been certain issues while implementing M1 Metrics CRUD, more specifically with GET operation.

Firstly to clearfiy the way on how do I test those operations after compiling changes:
I use Postman client application to send related HTTP requests to the Application Function's server (same idea as using `curl`). I simluate entire metrics streaming configuration with random data, just to make sure that operations are working properly. This is POST body:

```
{
    "metricsReportingConfigurationId": "100",
    "scheme": "scheme1",
    "dataNetworkName": "my_network1",
    "isReportingInterval": true,
    "reportingInterval": 60,
    "isSamplePercentage": true,
    "samplePercentage": 0.5,
    "urlFilters": ["filter1", "filter2"],
    "samplingPeriod": 3,
    "metrics": ["metric1", "metric2"]
}
```
In my current code to process [POST](https://github.com/stojkovicv/rt-5gms-application-function/blob/9a410fe5567639c379fb0ccb197537faac8bb35e/src/5gmsaf/msaf-m1-sm.c#L547) request, I invoke [internal functions](https://github.com/stojkovicv/rt-5gms-application-function/blob/9a410fe5567639c379fb0ccb197537faac8bb35e/src/5gmsaf/metrics-reporting-configuration.c) that will assign UUID to the metrics configuration, store received data into provisioning session as part of hash mapping mechanism (using metrics ID as the key).
This internal logic relays on OpenAPI `msaf_api_metrics_reporting_configuration_create()` that has been invoked.
There is a certain discrepancy here, since this function requires `metrics_reporting_configuration_id` as an argument, but that ID is supposed to be dynamically generated by AF. Neverthless, I send this ID in the POST body and AF overwrites with an generated UUID. Server responds with `201 Created`, all metrics configuration's IDs are visible as part of provisioning session JSON subarray `metricsReportingConfigurationIds`, according to the TS26.512(v17.7.0).

Now regarding GET operation:
I added code for auxiliary function to retrieve specific metrics configuration by its ID [here](https://github.com/stojkovicv/rt-5gms-application-function/blob/9a410fe5567639c379fb0ccb197537faac8bb35e/src/5gmsaf/metrics-reporting-configuration.c#L101). Then I invoke OpenAPI function `msaf_api_metrics_reporting_configuration_convertToJSON()` to convert this object into JSON format. 

However, this code results with an error:
```
Thread 2 "open5gs-msafd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff473a640 (LWP 97782)]
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.

```

I'm not sure what is the problem here, I can not find any issues with my GET operation [code](https://github.com/stojkovicv/rt-5gms-application-function/blob/9a410fe5567639c379fb0ccb197537faac8bb35e/src/5gmsaf/msaf-m1-sm.c#L959). I assume that there might be an error in the way how configuration object is intially created with [POST](https://github.com/stojkovicv/rt-5gms-application-function/blob/9a410fe5567639c379fb0ccb197537faac8bb35e/src/5gmsaf/msaf-m1-sm.c#L547), and retrieval attempt is failing in parsing badly formatted configuration.

**Comment by rjb1000** [comment]
@stojkovicv: I agree that the *metricsReportingConfigurationId* should be assigned by the 5GMS AF on resource creation. If you supply a value, it should be ignored by the 5GMS AF. The fact that it isn't being ignored sounds like it could be a bug.

Please could you raise a new bug issue so that this can be investigated by @davidjwbbc and @devbbc? Thanks.
