### ISSUE TITLE
Implement M3 client

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#7]
# Feature description
Using OpenAPI YAML interface definition files, implement an M3 client for the 5GMSd AF that communicates with one or more instances of the 5GMSd AS developed in #30.
* Provision and manage Server Certificate resources available to the test client as local X.509 PEM files.
  * Create, Retrieve, Update, Destroy.
* Provision and manage Content Hosting Configuration resources available to the test client as local JSON files.
  * Create, Retrieve, Update, Destroy.
  * Purge the associated content cache.

Note that there is nothing to stimulate the destruction of Content Hosting Configurations and server certificates in the Application Function as part of the scope of the M3 Link project. (Destruction only comes into play when the M1 provisioning is implemented.) Nevertheless, the destruction operations should still be implemented as part of the scope of this feature. These operations can be tested by placing a fake event on the Open5GS event loop.

# Relevant specifications and corresponding sections
- TS 26.512.
- Pre-standardisation M3 Open API YAML interface definition files - see 5G-MAG/rt-common-shared#12.

# Additional context
In the first instance, the 5GMSd AF only knows about a single Content Hosting Configuration, loaded from a local JSON file, but passive provision should be made for it to maintain provisioning state for one Content Hosting Configuration per Provisioning Session, indexed by `provisioningSessionId`.

The JSON configuration file for the 5GMSd AF needs to be enhanced to list the FQDN or IP address of the 5GMSd AS that it is managing. Passive provision should be made in this configuration to list multiple 5GMSd AS instances.

# Implementation design
Due to the event driven nature of Open5GS NFs the design is split into multiple events and actions which operate on application context of the 5GMS Application Function. To make this simple at first, we will start with a mapping of the provisioning session content hosting configuration to one application server, i.e. the application server deals with all distribution configurations in the content hosting configuration. The application context will therefore hold an array of application server state structures which will each hold:
- A pointer to the application server configuration this state is related to.
- A list of provisioning sessions assigned to the application server.
- A, possibly uninitialised, list of certificates currently known to the application server.
- A list of certificates that need uploading (adding or updating) on the application server.
- A list of certificates that need deleting from the application server.
- A, possibly uninitialised, list of content hosting configurations currently known to the application server.
- A list of content hosting configurations to upload (add or update) on the application server.
- A list of content hosting configurations to delete from the application server.

## When a ContentHostingConfiguration arrives
Ultimately this will happen on the M1 interface, but for now this is triggered by loading the configured JSON file.

1. Parse the ContentHostingConfiguration and check for syntax correctness (done by openapi-generator created bindings)
2. Verify the ContentHostingConfiguration and raise an error if the configuration is incorrect
    i. Check that the application function has been configured with the certificates referenced by any `distributionConfigurations.certificateId` fields.
4. Choose an application server to implement this configuration (for now just take the first on the list, we will add some load balancing later).
3. For each `distributionConfigurations.certificateId`, add the `provisioningSessionId` + `':'` + `distributionConfigurations.certificateId` to the application server state list of certificates to upload.
4. Add the provisioningSessionId for the ContentHostingConfiguration to the application server state list of content hosting configurations to upload.
5. Call a function to perform the next M3 operation for the chosen application server.

## Function to perform the next M3 operation for a given application server state
This will perform one step in synchronising the application server with the desired state (lists of certificates and content hosting configurations to upload or delete).

1. If the current known certificates list in the application server state is uninitialised
    1. Send a `GET /certificates` request to the application server.
    2. Return
2. If there are entries in the upload certificates list in the application server state
    1. If the first entry in the upload certificates list also appears in the currently known certificates list
        1. Send the certificate referred to by the first entry from the upload certificates list using a `PUT /certificates/<certificateId>`  to the application server.
    2. Otherwise
        1. Send the certificate referred to by the first entry from the upload certificates list using a `POST /certificates/<certificateId>`  to the application server.
    3. Return
3. If the current known content hosting configurations list in the application server state is uninitialised
    1. Send a `GET /content-hosting-configurations` request to the application server.
    2. Return
4. If there are entries in the upload content hosting configurations list in the application server state
    1. If the first entry in the upload content hosting configurations list also appears in the currently known content hosting configurations list
        1. Send the content hosting configuration referred to by the provisioning session Id from the first entry from the upload content hosting configurations list using a `PUT /content-hosting-configurations/<provisioningSessionId>`  to the application server.
    2. Otherwise
        1. Send the content hosting configuration referred to by the provisioning session Id from first entry from the upload content hosting configurations list using a `POST /content-hosting-configurations/<provisioningSessionId>`  to the application server.
    3. Return
5. If there are entries in the delete content hosting configurations list in the application server state
    1. Using the id from the first entry in the delete content hosting configurations list, send `DELETE /content-hosting-configurations/<id>` to the application server.
    2. Return
6. If there are entries in the delete certificates list in the application server state
    1. Using the id from the first entry in the delete certificates list, send `DELETE /certificates/<id>` to the application server.
    2. Return
7. Return

## When a client response is received
The following actions assume 2XX responses, if an error response is received from an application server it should be dealt with appropriately.

1. If the request was for `GET /certificates`
    1. Parse the body of the response as a JSON array and return an error if bad syntax.
    2. Initialise or empty the known certificates list in the application server state associated with the request
    3. Populate the list with the array entries
    4. Perform the next M3 operation for the application server state
2. If the request was for `POST /certificates/<id>`
    1. Remove the entry for id from the upload certificates list in the application server state associated with the request
    2. Add the entry for id to the current known certificates list in the application server state associated with the request
    3. Perform the next M3 operation for the application server state
3. If the request was for `PUT /certificates/<id>`
    1. Remove the entry for id from the upload certificates list in the application server state associated with the request
    2. Perform the next M3 operation for the application server state
4. If the request was for `DELETE /certificates/<id>`
    1. Remove the entry for id from the delete certificates list in the application server state associated with the request
    2. Remove the entry for id from the current known certificates list in the application server state associated with the request
    3. Perform the next M3 operation for the application server state
5. If the request was for `GET /content-hosting-configurations`
    1. Parse the body of the response as a JSON array and return an error if bad syntax.
    2. Initialise or empty the known content hosting configurations list in the application server state associated with the request
    3. Populate the list with the array entries
    4. Perform the next M3 operation for the application server state
6. If the request was for `POST /content-hosting-configurations/<id>`
    1. Remove the entry for id from the upload content hosting configurations list in the application server state associated with the request
    2. Add the entry for id to the current known content hosting configurations list in the application server state associated with the request
    3. Perform the next M3 operation for the application server state
7. If the request was for `PUT /content-hosting-configurations/<id>`
    1. Remove the entry for id from the upload content hosting configurations list in the application server state associated with the request
    2. Perform the next M3 operation for the application server state
8. If the request was for `DELETE /content-hosting-configurations/<id>`
    1. Remove the entry for id from the delete content hosting configurations list in the application server state associated with the request
    2. Remove the entry for id from the current known content hosting configurations list in the application server state associated with the request
    3. Perform the next M3 operation for the application server state

This design means that any wanted updates to an application server's state can be set in the upload and delete lists in the specific application server state, and the appropriate operations will be performed in sequence in order to achieve that state. At the end of which the upload and delete lists should be empty and no more actions will be performed.

**Comment by devbbc** [comment]
The Application Function considers "{provisioningSessionId}:{certificateId}" as its `afUniqueCertificateId`.

Modified the code so that any `certificateId`s in the distribution configurations are now prefixed with the Provisioning Session Id, when a contentHostingConfiguration is to be sent to the AF.

Tested the working of the M3 interface by running this Application Function against the[ M3 server](5G-MAG/rt-5gms-application-server/issues/30) of the Application Server. They worked as expected.
