### ISSUE TITLE
Import TS 26.512 V17.6.0 OpenAPI files

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#81]
TS 26.512 V17.6.0, agreed at SA4#124 (Berlin) and approved at SA#100 (Taipei) has changes in the following OpenAPI files:
- _M1_ServerCertificatesProvisioning_
  - JSON array of domain name aliases added to the `POST` message body of the _createOrReserveServerCertificate_ operation.
- _M1_ContentHostingProvisioning_
  - Data type _MediaEntryPoint_ renamed to _M1MediaEntryPoint_ to avoid tripping up OpenAPI Generator<sup>†</sup>.
- _M1_PolicyTemplatesProvisioning_
  - _stateReason_ added to _PolicyTemplate_ data type.
- _M5_ServiceAccessInformation_
  - Data type _MediaEntryPoint_ renamed to _M5MediaEntryPoint_ to avoid tripping up OpenAPI Generator<sup>†</sup>.

The updated API files can be downloaded from here:

- https://forge.3gpp.org/rep/all/5G_APIs/-/tree/TSG100-Rel17

<sup>†</sup> The changes for _M1MediaEntryPoint_ and _M5MediaEntryPoint_ were added to https://github.com/5G-MAG/rt-common-shared/tree/main/5gms/5G_APIs-overrides in advance of 3GPP approval to allow development to progress, and these API overrides now need to be unwound.

**Comment by davidjwbbc** [comment]
Changes to AF to pick new API version needs to be PR'd
