### ISSUE TITLE
Implement Consumption Reporting Provisioning API at reference point M1

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#88]
## Description 

Add the M1 `{apiRoot}/3gpp-m1/v2/provisioning-session/{provisioning-session-id}/consumption-reporting-configuration` POST/GET/PUT/DELETE operations.

## References

TS 26.512 v17.6.0
- Clauses 4.3.8 & 7.7
- Annex C.3.6

**Comment by davidjwbbc** [comment]
I've added the code for the POST, GET & PUT methods. Yet to add DELETE and also need to test all operations.

**Comment by davidjwbbc** [comment]
Added code for DELETE and OPTIONS methods and updated the M1 Python tools to take new consumption reporting commands and configurations.

Also fixed a missing OPTIONS method for content protocols discovery.

That now leaves the testing (and documenting the results) left to do, which will be easier now the M1 Python tools are updated.

**Comment by devbbc** [comment]
Reviewed the `feature/m1-consumption-reporting` branch. Looks good. 

So, will approve the PR https://github.com/5G-MAG/rt-5gms-application-function/pull/92
