### ISSUE TITLE
Implement Consumption Reporting API at reference point M5

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#89]
## Introduction

The *ConsumptionReporting* API on the interface at reference point M5 is used by the 5GMS Application Function to receive consumption reports. The reports are submitted by the MediaSessionHandler in response to parameters set in the `ServiceAccessInformation.clientConsumptionReportingConfiguration` field of a service access information response (see #93).

### HTTP Methods

The API shall implement processing of requests for two HTTP methods, POST & OPTIONS.

#### POST - submitConsumptionReport

The `POST` method shall be implemented according to TS 26.512 clause 11.3. However, since there is, at present, no Data Collection AF in the implementation of the 5GMS Application Function, the contents of the consumption reports shall be stored to the local file-system (see [Storage of Received Reports](#storage-of-received-reports)).

#### OPTIONS - API introspection

The 'OPTIONS' method, used for API interface introspection, shall report that only `POST` and `OPTIONS` methods are allowed for URLs with a path of `{apiRoot}/3gpp-m5/v2/consumption-reporting/{provisioningSessionId}`.

### Storage of Received Reports

For the time being, consumption reports are simply written to disk by the 5GMS AF for manual inspection.

The reports should be stored in a folder nominated in the YAML configuration file for the 5GMS AF.

Each report received shall be stored to the local file store using a path with the following naming convention:

`<ProvisioningSessionId>`/consumption_reports/`<ConsumptionReport.reportingClientId>`_`<min(ConsumptionReport.consumptionReportingUnits[*].startTime)>`.json

where:
- `<ProvisioningSessionId>` comes from the provisioning session id given in the POST request URL path.
- `<ConsumptionReport.reportingClientId>` is the `reportingClientId` from the submitted ConsumptionReport.
- `<min(ConsumptionReport.consumptionReportingUnits[*].startTime)>` is the earliest `startTime` field from one of the `consumptionReportingUnits` array in the submitted ConsumptionReport in RFC3339 Internet Date/Time format (section 5.6) (this can be copied from the report).

## References

TS 26.512 (v17.6.0)
- Clauses 4.7.4 & 11.3
- Annex C.4.2

RFC 3339
- Section 5.6

**Comment by davidjwbbc** [comment]
Changed the reporting of the submitted consumption reports to storage on the local file store to match the proposal for QoE Metrics reports (issue #90).

**Comment by rjb1000** [comment]
@davidjwbbc: Rather than using the start time of the earliest consumption reporting unit in the storage filename, I wonder if it would be simpler to just use the timestamp at which the report is received by the 5GMS AF?

**Comment by davidjwbbc** [comment]
Code complete and just finishing some testing.

I've added a data-collection.c which has a `msaf_data_collection_store()` function which takes a set of parameters to use to make the storage file path, a file type and the file contents (as a nul terminated string). This function will use the configured data collection directory as the root for storage, ensure sub-directories are present for the final storage path and then write out the data file. This function may be useful to @stojkovicv for the metrics storage in #90.

Current development is on my fork on the [feature/m5-consumption-api](https://github.com/davidjwbbc/rt-5gms-application-function/tree/feature/m5-consumption-api) branch. Hoping to finish testing tomorrow and create the PR.

**Comment by davidjwbbc** [comment]
## Testing

To perform the tests I:
1. Created a local `msaf.yaml` configuration with the `msaf.dataCollectionDir` set to a suitable reports directory location.
1. Started up a 5GMS Application Server
1. Started the 5GMS Application Function with M5 Consumption Reporting API
1. Ran the `msaf-configuration` tool using the following streams.json:
    ```json
    {
    "aspId": "MyASPId",
    "appId": "BBCRD5GTestbed",
    "streams": {
	"default_crc": {
            "name": "Default CRC",
            "ingestURL": "https://example.com/",
            "distributionConfigurations": [
                { }
            ],
	    "consumptionReporting": {}
        },
        "crc_all": {
            "name": "CRC with all fields",
            "ingestURL": "https://example.com/media1/",
            "distributionConfigurations": [
                {
                    "entryPoint": {
                        "relativePath": "manifest.mpd",
                        "contentType": "application/dash+xml",
                        "profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
                    }
                }
            ],
	    "consumptionReporting": {
		"reportingInterval": 120,
		"samplePercentage": 50.0,
		"locationReporting": true,
		"accessReporting": true
	    }
        },
        "crc_no_access": {
            "name": "CRC with all fields except access reporting",
            "ingestURL": "https://example.com/media2/",
            "distributionConfigurations": [
                {
                    "entryPoint": {
                        "relativePath": "manifest.mpd",
                        "contentType": "application/dash+xml",
                        "profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
                    }
                }
            ],
            "consumptionReporting": {
                "reportingInterval": 60,
                "samplePercentage": 95.0,
                "locationReporting": false
            }   
        },
        "no_crc": {
            "name": "No CRC",
            "ingestURL": "https://example.com/media3/",
            "distributionConfigurations": [
                {
                    "entryPoint": {
                        "relativePath": "manifest.mpd",
                        "contentType": "application/dash+xml",
                        "profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
                    }
                }
            ]
        }
    },
    "vodMedia": [
	{
	    "name": "Stream with default CRC",
	    "stream": "default_crc",
	    "entryPoints": [
		{
                    "relativePath": "media4/manifest.mpd",
                    "contentType": "application/dash+xml",
                    "profiles": ["urn:mpeg:dash:profile:isoff-live:2011"]
                },
                {
                    "relativePath": "media4/master.m3u8",
                    "contentType": "application/vnd.apple.mpegurl"
                }
	    ]
	}
    ]
    }
    ```
1. Set some environment variables to hold several Provisioning Session Ids:
    ```bash
    ps=aaecb398-61cf-41ee-8845-17a454dd4393  # Provisioning session with Consumption Reporting Configuration (crc_no_access)
    ncps=ab2e3bec-61cf-41ee-8845-17a454dd4393  # Provisioning session without Consumption Reporting Configuration (no_crc)
    neps=does-not-exist  # Non-existant Provisioning Session
    ```
1. Fetched Service Access Information to show configuration was in effect:
    ```bash
    curl -vv 'http://127.0.0.22:7778/3gpp-m5/v2/service-access-information/'"$ps"
    ```
    Result is
    ```bash
    > GET /3gpp-m5/v2/service-access-information/aaecb398-61cf-41ee-8845-17a454dd4393 HTTP/1.1
    > Host: 127.0.0.22:7778
    > User-Agent: curl/8.0.1
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < Date: Tue, 03 Oct 2023 09:32:56 GMT
    < Connection: close
    < ETag: e9efd8730d2a2f64a38114ab6cfaa0ef1dfad2d091371936634770ab486cc2cf
    < Last-Modified: Tue, 03 Oct 2023 09:32:57 GMT
    < Cache-Control: max-age=60
    < Server: 5GMSAF-localhost/17 (info.title=M5_ServiceAccessInformation; info.version=2.3.0) rt-5gms-application-function/1.3.0
    < Content-Type: application/json
    < Content-Length: 570
    < 
    {
	"provisioningSessionId":	"aaecb398-61cf-41ee-8845-17a454dd4393",
	"provisioningSessionType":	"DOWNLINK",
	"streamingAccess":	{
		"entryPoints":	[{
				"locator":	"http://localhost/m4d/provisioning-session-aaecb398-61cf-41ee-8845-17a454dd4393/manifest.mpd",
				"contentType":	"application/dash+xml",
				"profiles":	["urn:mpeg:dash:profile:isoff-live:2011"]
			}]
	},
	"clientConsumptionReportingConfiguration":	{
		"reportingInterval":	60,
		"serverAddresses":	["http://127.0.0.22:7778/3gpp-m5/v2/"],
		"locationReporting":	false,
		"samplePercentage":	95
	}
    }
    ```
    Showing that the configuration took place. Also note that the `clientConsumptionReportingConfiguration.serverAddresses` contains one entry based on the request URL.
1. Post a consumption report:
    ```bash
    curl -vv -H 'Content-Type: application/json' --data '{"mediaPlayerEntry": "http://localhost/m4d/provisioning-session-'"$ps"'/manifest.mpd", "reportingClientId": "12345678-9abc-4def-0123-456789abcdef", "consumptionReportingUnits": [{"mediaConsumed": "v1", "startTime": "20231002095900", "duration": 60}]}' 'http://127.0.0.22:7778/3gpp-m5/v2/consumption-reporting/'"$ps"
    ```
    The response is:
    ```
    > POST /3gpp-m5/v2/consumption-reporting/aaecb398-61cf-41ee-8845-17a454dd4393 HTTP/1.1
    > Host: 127.0.0.22:7778
    > User-Agent: curl/8.0.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 285
    > 
    < HTTP/1.1 204 No Content
    < Date: Tue, 03 Oct 2023 09:32:59 GMT
    < Server: 5GMSAF-localhost/17 (info.title=M5_ConsumptionReporting; info.version=2.1.0) rt-5gms-application-function/1.3.0
    < Location: /3gpp-m5/v2/consumption-reporting/aaecb398-61cf-41ee-8845-17a454dd4393
    < 
    ```
    The report is accepted and appears on disk in the configured data collection dir as `aaecb398-61cf-41ee-8845-17a454dd4393/consumption_reports/12345678-9abc-4def-0123-456789abcdef_20231002095900.json` (note if the `msaf.dataCollectionDir` configuration file parameter has not been set then the report is not stored to disk).
    Also note the `Server` header in the response indicates the `M5_ConsumptionReporting` API is in use.
1. Post a consumption report to a non-existent Provisioning Session:
    ```bash
    curl -vv -H 'Content-Type: application/json' --data '{"mediaPlayerEntry": "http://localhost/m4d/provisioning-session-'"$neps"'/manifest.mpd", "reportingClientId": "12345678-9abc-4def-0123-456789abcdef", "consumptionReportingUnits": [{"mediaConsumed": "v1", "startTime": "20231002095900", "duration": 60}]}' 'http://127.0.0.22:7778/3gpp-m5/v2/consumption-reporting/'"$neps"
    ```
    The response is:
    ```
    > POST /3gpp-m5/v2/consumption-reporting/does-not-exist HTTP/1.1
    > Host: 127.0.0.22:7778
    > User-Agent: curl/8.0.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 279
    > 
    < HTTP/1.1 404 Not Found
    < Date: Tue, 03 Oct 2023 10:34:10 GMT
    < Server: 5GMSAF-localhost/17 (info.title=M5_ConsumptionReporting; info.version=2.1.0) rt-5gms-application- function/1.3.0
    < Content-Type: application/problem+json
    < Content-Length: 204
    < 
    {
	"type":	"/3gpp-m5/v2",
	"title":	"Not Found",
	"status":	404,
	"detail":	"Provisioning session [does-not-exist] not found for Consumption Report",
	"instance":	"/consumption-reporting/does-not-exist"
    }
    ```
    The response is a 404 as expected with the problem detail indicating that the provisioning session does not exist.
1. Post a consumption report to an existing Provisioning Session which is not configured for Consumption Reports:
    ```bash
    curl -vv -H 'Content-Type: application/json' --data '{"mediaPlayerEntry": "http://localhost/m4d/provisioning-session-'"$ncps"'/manifest.mpd", "reportingClientId": "12345678-9abc-4def-0123-456789abcdef", "consumptionReportingUnits": [{"mediaConsumed": "v1", "startTime": "20231002095900", "duration": 60}]}' 'http://127.0.0.22:7778/3gpp-m5/v2/consumption-reporting/'"$ncps"
    ```
    The output is:
    ```
    > POST /3gpp-m5/v2/consumption-reporting/ab2e3bec-61cf-41ee-8845-17a454dd4393 HTTP/1.1
    > Host: 127.0.0.22:7778
    > User-Agent: curl/8.0.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 279
    > 
    < HTTP/1.1 404 Not Found
    < Date: Tue, 03 Oct 2023 10:35:04 GMT
    < Server: 5GMSAF-localhost/17 (info.title=M5_ConsumptionReporting; info.version=2.1.0) rt-5gms-application-function/1.3.0
    < Content-Type: application/problem+json
    < Content-Length: 279
    < 
    {
	"type":	"/3gpp-m5/v2",
	"title":	"Not found",
	"status":	404,
	"detail":	"No ConsumptionReportingConfiguration for Provisioning Session [ab2e3bec-61cf-41ee-8845-17a454dd4393], cannot accept reports",
	"instance":	"/consumption-reporting/ab2e3bec-61cf-41ee-8845-17a454dd4393"
    }
    ```
    The response indicates that the provisioning session is not configured for consumption reports and is treated as consumption reporting is not found at this location (could be changed to "400 Bad Request").
1. Post a consumption report with the wrong content type:
    ```bash
    curl -vv H 'Content-Type: application/json+bogus' --data '{"mediaPlayerEntry": "http://localhost/m4d/provisioning-session-'"$ps"'/manifest.mpd", "reportingClientId": "12345678-9abc-4def-0123-456789abcdef", "consumptionReportingUnits": [{"mediaConsumed": "v1", "startTime": "20231002095900", "duration": 60}]}' 'http://127.0.0.22:7778/3gpp-m5/v2/consumption-reporting/'"$ps"
    ```
    The output is:
    ```
    > POST /3gpp-m5/v2/consumption-reporting/aaecb398-61cf-41ee-8845-17a454dd4393 HTTP/1.1
    > Host: 127.0.0.22:7778
    > User-Agent: curl/8.0.1
    > Accept: */*
    > Content-Type: application/json+bogus
    > Content-Length: 279
    > 
    < HTTP/1.1 415 Unsupported Media Type
    < Date: Tue, 03 Oct 2023 10:35:32 GMT
    < Content-Type: application/problem+json
    < Server: 5GMSAF-localhost/17 (info.title=M5_ConsumptionReporting; info.version=2.1.0) rt-5gms-application-function/1.3.0
    < Content-Length: 281
    < 
    {
	"type":	"/3gpp-m5/v2",
	"title":	"Malformed request body",
	"status":	415,
	"detail":	"Unrecognised content type for Consumption Report for Provisioning Session [aaecb398-61cf-41ee-8845-17a454dd4393]",
	"instance":	"/consumption-reporting/aaecb398-61cf-41ee-8845-17a454dd4393"
    }
    ```
    A 415 response is returned if the consumption report is sent with anything other than "application/json" as its content type.
1. Invalid HTTP operation:
    ```bash
    curl -vv -X PUT -H 'Content-Type: application/json' --data '{"mediaPlayerEntry": "http://localhost/m4d/provisioning-session-'"$ps"'/manifest.mpd", "reportingClientId": "12345678-9abc-4def-0123-456789abcdef", "consumptionReportingUnits": [{"mediaConsumed": "v1", "startTime": "20231002095900", "duration": 60}]}' 'http://127.0.0.22:7778/3gpp-m5/v2/consumption-reporting/'"$ps"
    ```
    The output is:
    ```
    > PUT /3gpp-m5/v2/consumption-reporting/aaecb398-61cf-41ee-8845-17a454dd4393 HTTP/1.1
    > Host: 127.0.0.22:7778
    > User-Agent: curl/8.0.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 279
    > 
    < HTTP/1.1 405 Method Not Allowed
    < Date: Tue, 03 Oct 2023 10:54:12 GMT
    < Server: 5GMSAF-localhost/17 (info.title=M5_ConsumptionReporting; info.version=2.1.0) rt-5gms-application- function/1.3.0
    < Content-Type: application/problem+json
    < Content-Length: 226
    < 
    {
	"type":	"/3gpp-m5/v2",
	"title":	"Method Not Allowed",
	"status":	405,
	"detail":	"Method [PUT] not implemented for M5 Consumption Reporting API",
	"instance":	"/consumption-reporting/aaecb398-61cf-41ee-8845-17a454dd4393"
    }
    ```
    Only `POST` and `OPTIONS` methods are allowed, a 405 response will be sent for other HTTP methods.

**Comment by davidjwbbc** [comment]
I'm still in two minds as to whether trying to post a consumption report to a provisioning session that doesn't have consumption reporting should result in a 404 not found (what I've implemented - consumption reporting is not found for this provisioning session) or a 400 Bad Request (attempt to post consumption report without AP configuration).

**Comment by rjb1000** [comment]
Some comments on the error cases, @davidjwbbc:

* For the non-existent Provisioning Session ID case, the error message doesn't correctly cite the erroneous identifier in the _detail_ and _instance_ parameters.
* When consumption reporting isn't configured for a Provisioning Session, I'm not sure that _404 Not Found_ is the best response because the request URL is fine. _400 Bad Request_ seems more appropriate in this case.
* For the error where the media type is not correct, it would be helpful if the `detail` parameter indicated which media type(s) are required. Also, "Malformed request body" seems wrong for the _title_ parameter.
