### ISSUE TITLE
QoE metrics reporting: Store received reports as local files

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#90]
# Background

Prior to Release 17, there was no support for exposing events relating the 5G Media Streaming to downstream entities. From Release 17 onwards, a **Data Collection AF** may be instantiated in the 5GMS AF which implements the _Naf_EventExposure_ service and offers event exposure to downstream service consumers. However, the specification of this has been found to be unworkable in Release 17 and attempts to rectify this are ongoing in 3GPP.

A reference implementation of the Data Collection AF is a medium-term ambition.

# Specification

For the time being, QoE metrics reports are simply written to disk by the 5GMS AF for manual inspection.

The reports should be stored in a folder nominated in the YAML configuration file for the 5GMS AF.

Reports should be stored using the following file naming convention:

`<ProvisioningSessionID>`/metrics_reports_`<MetricsReportingConfigurationID>`/`<ReceptionReport@clientId>`\_`<ReceptionReport/QoeReport@recordingSessionId>`\_`<ReceptionReport/QoeReport@reportTime>`.xml.

(In our reference implementation, the Provisioning Session ID and Metrics Reporting Configuration ID are both UUIDs, so this will be reflected in the folder structure above.)

Note the following:

1. `ReceptionReport@clientId` is optional in the reporting schema in clause 10.6.2 of TS 26.247.
    * The value `anonymous` should be used if the attribute is omitted from a report.
2. `ReceptionReport/QoeReport@recordingSessionId` is optional in the reporting schema in clause 10.6.2 of TS 26.247.
    * The value `nosession` should be used if the attribute is omitted from a report.
    * It would be useful for the Media Session Handler to start populating this optional attribute.

**Comment by dsilhavy** [comment]
Required changes were merged in #143
