### ISSUE TITLE
M1 update operation for Consumption Reporting - Handling of invalid configuration

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#98]
## Describe the bug
When updating a consumption reporting configuration via the M1 interface and providing an invalid configuration, the previous configuration seems to be discarded.

Related to that it looks like we cannot recover from an invalid state even if we provide valid values again. The current solution here is to delete the consumption reporting configuration and provide a new valid configuration

### 1. Create a configuration

![273154305-e5ef6119-2c1b-436d-892b-fccf24bf1cd7](https://github.com/5G-MAG/rt-5gms-application-function/assets/2427039/58ec376e-3b59-4414-8d23-40153c4c8591)

### 2. Update the configuration with an invalid sample percentage

![273155311-0347220e-c8b6-4076-83a1-0ff2f3033edf](https://github.com/5G-MAG/rt-5gms-application-function/assets/2427039/04e97abe-9748-4ec5-b3e2-4461e38b13ed)

### 3. Try to update with valid values again

![273156227-26d2e03d-1c6f-4c5f-9ec6-b1d2d980ff3a](https://github.com/5G-MAG/rt-5gms-application-function/assets/2427039/3dc691f8-2b39-463b-8b96-ab9d6e96d58a)

**Comment by davidjwbbc** [comment]
I've added some extra validation to the AF code.

An attempt to set a percentage outside [0.0 .. 100.0] will result in an error response now.

```
$ m1-session set-consumption-reporting -p $ps -s 150
Communication error: [400] M1 operation failed: {
	"type":	"/3gpp-m1/v2",
	"title":	"Bad request.",
	"status":	400,
	"detail":	"Bad ConsumptionReportingConfiguration for provisioning session [2c9798bc-645b-41ee-a954-433da8d15fa6]: Bad value: samplePercentage out of range",
	"instance":	"/provisioning-sessions/2c9798bc-645b-41ee-a954-433da8d15fa6/consumption-reporting-configuration"
}
```

... and *reportInterval* must be greater than 0 too.

```
$ m1-session set-consumption-reporting -p $ps -i 0
Communication error: [400] M1 operation failed: {
	"type":	"/3gpp-m1/v2",
	"title":	"Bad request.",
	"status":	400,
	"detail":	"Bad ConsumptionReportingConfiguration for provisioning session [2c9798bc-645b-41ee-a954-433da8d15fa6]: Bad value: reportingInterval must be greater than 0",
	"instance":	"/provisioning-sessions/2c9798bc-645b-41ee-a954-433da8d15fa6/consumption-reporting-configuration"
}
```

**Comment by rjb1000** [comment]
@davidjwbbc: Please could you include the valid range (0.0 to 100.0) in the human-readable error message returned in the `detail` property?
