### ISSUE TITLE
M5 Service Access Information - Consumption Reporting Configuration - Missing accessReporting

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-application-function#99]
## Description
In the current version of the `ServiceAccessInformation.clientConsumptionReportingConfiguration` the `accessReporting` field is not always present, as an example:

````json
{
	"provisioningSessionId":	"33a4aaa0-6429-41ee-b472-0ba8822ffea4",
	"provisioningSessionType":	"DOWNLINK",
	"streamingAccess":	{
	},
	"clientConsumptionReportingConfiguration":	{
		"reportingInterval":	60,
		"serverAddresses":	["http://127.0.0.24:7777/3gpp-m5/v2/"],
		"locationReporting":	false,
		"samplePercentage":	100
	}
}
````

Based on the specification TS 26.512 it is not quite clear if the `accessReporting` field is mandatory or not. For that reason, we created an issue in the standards repo: https://github.com/5G-MAG/Standards/issues/93. Once this is clarified we potentially need to adjust the implementation accordingly.

**Comment by davidjwbbc** [comment]
We normally assume the Table is correct and that the Annex is inconsistent in these cases.

**Comment by davidjwbbc** [comment]
The ServiceAccessInformation below shows the default clientConsumptionReportingConfiguration (when consumption reporting is added, via M1, to the provisioning session with no *reportingInterval*, *samplePercentage*, *accessReporting* or *locationReporting* fields set) with the fix in place.

```json
{
	"provisioningSessionId":	"2c9798bc-645b-41ee-a954-433da8d15fa6",
	"provisioningSessionType":	"DOWNLINK",
	"streamingAccess":	{
	},
	"clientConsumptionReportingConfiguration":	{
		"reportingInterval":	10,
		"serverAddresses":	["http://127.0.0.22:7778/3gpp-m5/v2/"],
		"locationReporting":	false,
		"accessReporting":	false,
		"samplePercentage":	100
	}
}

**Comment by rjb1000** [comment]
Thanks for raising this @dsilhavy. It seems to me that the workaround implemented by @davidjwbbc (adding `"accessReporting": false` when the property is omitted at M1) is the right one for the time being because it satisfies the specification in TS 26.512 V17.6.0.

I'll respond separately about the specification anomaly on 5G-MAG/Standards#93.
